version: '3.8'

services:
  heat_up:
    build: .
    container_name: heat_up_service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TELEGRAM_API_BASE_URL=${TELEGRAM_API_BASE_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY:-}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - heat_up_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  heat_up_network:
    driver: bridge

